### PR TITLE
#160786258 Refactor code to improve UX

### PR DESCRIPTION
**Pull request by billkabanga**
### What does this PR do?
Refactor code to improve the user experience.
#### Description of the task to be completed?
Remove dropdown lists from the `login` and `signup` links on home page.
Client and Admin users should have single `signup` and `login` forms.
Roles to be specified using `radio buttons`
Create a javascript file to handle the functionality of the radio buttons for form action.
#### How should this be manually tested?
This can only be tested once the PR is merged. 
#### What are the related pivotal tracker stories?
#160786258
#### Screenshots.
signup
login
home

### CODE REVIEW

**Comment by danielsd12** [comment]
bill this gives sense now i can get a bigger picture of how to implement a good sign up and sign in pages

**Comment by kdaglas** [comment]
ok, this is better, as a user I won't have to go through a lot of dropdowns, navigations to get to where I need to be, there is only that one page I need to access to create the account... good logic.

**Comment by aayebare** [comment]
great work with the radio buttons ..looks neat

**Comment by d-rita** [comment]
Good UI/UX for signup and login pages.

**Comment by nanfuka** [comment]
great. this is a lot more user friendly than the drop down lists

**Comment by Sebuliba-Adrian** [comment]
LGTM. 👍

**Review by Sebuliba-Adrian — APPROVED** [review]

**Pull request merged**
