### PR TITLE
Code Refactor PR

### PR DESCRIPTION
**Pull request by billkabanga**
**What does this PR do?**
Reduces the cognitive complexity of code with some encapsulation.
Creates class methods for the orders model.
Adds validation for contact input.
Improves test coverage.
**How can this be tested?**
Please follow the readme for this branch on testing the endpoints.
Click on the test coverage badge for the ratings.
**What is the related pivotal tracker story?**
* #160696487

### CODE REVIEW

**Comment by walimike** [comment]
I have gone through your changes, and everything is in order

**Comment by ekumamait** [comment]
Very neat code Bill nice work

**Comment by Phionamary** [comment]
Bill this is great work.  All your code is organised,  and you followed rubric to the dot.  👏

**Comment by joelethan** [comment]
Neat work  @billkabanga , and good job on the 100% coverage.

**Comment by Luleherll** [comment]
well done @billkabanga

**Pull request merged**
